"""
This module contains four napari widgets declared in
different ways:

- a pure Python function flagged with `autogenerate: true`
    in the plugin manifest. Type annotations are used by
    magicgui to generate widgets for each parameter. Best
    suited for simple processing tasks - usually taking
    in and/or returning a layer.
- a `magic_factory` decorated function. The `magic_factory`
    decorator allows us to customize aspects of the resulting
    GUI, including the widgets associated with each parameter.
    Best used when you have a very simple processing task,
    but want some control over the autogenerated widgets. If you
    find yourself needing to define lots of nested functions to achieve
    your functionality, maybe look at the `Container` widget!
- a `magicgui.widgets.Container` subclass. This provides lots
    of flexibility and customization options while still supporting
    `magicgui` widgets and convenience methods for creating widgets
    from type annotations. If you want to customize your widgets and
    connect callbacks, this is the best widget option for you.
- a `QWidget` subclass. This provides maximal flexibility but requires
    full specification of widget layouts, callbacks, events, etc.

References:
- Widget specification: https://napari.org/stable/plugins/building_a_plugin/guides.html#widgets
- magicgui docs: https://pyapp-kit.github.io/magicgui/

Replace code below according to your needs.
"""

from magicgui import magic_factory
from magicgui.widgets import CheckBox, Container, create_widget
import napari
import napari.utils
import napari.utils.notifications
from qtpy.QtWidgets import QHBoxLayout, QVBoxLayout, QPushButton, QCheckBox, QWidget, QLabel, QDoubleSpinBox, QTabWidget, QComboBox, QTableWidget, QTableWidgetItem, QHeaderView, QAbstractItemView
from qtpy.QtCore import Qt, QLocale
from qtpy.QtGui import QColor
import brimfile as brim
from brimfile.subtypes import single_point_VIPA
import numpy as np
from scipy import interpolate

try:
    import matplotlib.pyplot as plt
    from matplotlib.backends.backend_qt5agg import FigureCanvas
except ImportError as matplotlib_import_error:
    plt = None
    FigureCanvas = None
    _MATPLOTLIB_IMPORT_ERROR = matplotlib_import_error
else:
    _MATPLOTLIB_IMPORT_ERROR = None



# if we want even more control over our widget, we can use
# magicgui `Container`
class SpectraTools(Container):
    def __init__(self, viewer: "napari.viewer.Viewer"):
        if _MATPLOTLIB_IMPORT_ERROR is not None:
            raise ImportError( "matplotlib is required for Spectra Analysis Tools. Run "
                "`pip install 'brillouin-imaging[plotting]'`") from _MATPLOTLIB_IMPORT_ERROR

        super().__init__()
        self._viewer = viewer

        # Plot spectrum matplotlib figure
        self.fig_plot_spectrum, self.ax_plot_spectrum = plt.subplots()
        self.fig_plot_spectrum.set_layout_engine('constrained')
        self.fig_plot_spectrum.patch.set_alpha(0)
        self.ax_plot_spectrum.set_xlabel('Frequency []', color='white')
        self.ax_plot_spectrum.set_ylabel('PSD', color='white')
        self.ax_plot_spectrum.tick_params(axis='x', colors='white')
        self.ax_plot_spectrum.tick_params(axis='y', colors='white')
        self.ax_plot_spectrum.yaxis.label.set_color('white')
        self.ax_plot_spectrum.xaxis.label.set_color('white')
        self.ax_plot_spectrum.set_ylim(0,1)   # 37 41 49
        self.spectrum_ymax = 0
        self.spectrum_ymin = 1E6

        # Plot regional spectra matplotlib figure
        self.fig_regional_spectra, self.ax_regional_spectra = plt.subplots()
        self.fig_regional_spectra.set_layout_engine('constrained')
        self.fig_regional_spectra.patch.set_alpha(0)
        self.ax_regional_spectra.set_xlabel('Frequency []', color='white')
        self.ax_regional_spectra.set_ylabel('PSD', color='white')
        self.ax_regional_spectra.tick_params(axis='x', colors='white')
        self.ax_regional_spectra.tick_params(axis='y', colors='white')
        self.ax_regional_spectra.yaxis.label.set_color('white')
        self.ax_regional_spectra.xaxis.label.set_color('white')

        # Plot VIPA raw image matplotlib figure
        self.fig_vipa_rawdata, self.ax_vipa_rawdata = plt.subplots()
        self.fig_vipa_rawdata.set_layout_engine('constrained')
        self.fig_vipa_rawdata.patch.set_alpha(0)
        self.ax_vipa_rawdata.set_axis_off()

        # connect your own callbacks
        self._connect_mouse_events()

        # Tabs - add different widgets
        tabs = QTabWidget()
        self._tabs = tabs
        tabs.setTabPosition(QTabWidget.TabPosition.North)
        tabs.setMovable(True)
        tabs.setDocumentMode(True)
        tabs.tabBar().setDrawBase(False)
        tabs.setStyleSheet("""
            QTabBar::tab {
                background: #3F4852;         /* Simple background color */
                color: #D1D2D4;                 /* Text color */
                padding: 6px 16px;
                margin-right: 2px;           /* Space between tabs */
                min-width: 80px;
                border-bottom: none; /* remove the dividing line */
                border: none;
            }
            QTabBar::tab:selected {
                background: #58626D;         /* Background for selected tab */
                color: #D1D2D4;
            }
            QTabBar::tab:!selected {
                background: #3F4852;         /* No shading for unselected tabs */
            }
            QTabBar {
                alignment: left;
                qproperty-drawBase: 0;
                background: transparent;
            } 
            QTabWidget::pane {
                border: none;
                background: transparent;
            }
            """)

        # Inspect metadata tab
        inspect_metadata_widget = QWidget()
        inspect_metadata_layout = QVBoxLayout()
        inspect_metadata_widget.setLayout(inspect_metadata_layout)

        inspect_metadata_text = QLabel(text='Inspect metadata of the active Brillouin layer. Select a Brillouin layer to display its metadata here.')
        inspect_metadata_text.setStyleSheet("color: #626972;")
        inspect_metadata_text.setAlignment(Qt.AlignCenter)
        inspect_metadata_text.setWordWrap(True)
        inspect_metadata_layout.addWidget(inspect_metadata_text)

        self._metadata_table = QTableWidget(0, 2)
        self._metadata_table.horizontalHeader().setVisible(False)
        #self._metadata_table.setHorizontalHeaderLabels(["Key", "Value"])
        self._metadata_table.horizontalHeader().setStretchLastSection(True)
        self._metadata_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeToContents)
        self._metadata_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self._metadata_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self._metadata_table.verticalHeader().setVisible(False)
        self._metadata_table.setStyleSheet("""
                QTableWidget {
                    gridline-color: #3F4852;
                }
            """)
        inspect_metadata_layout.addWidget(self._metadata_table)

        # Spectrum Plotting tab
        spectrum_plotting_text = QLabel(text='Plot Brillouin spectrum of a single pixel in an active brimfile layer. Select a brimfile layer and click on a pixel.')
        spectrum_plotting_text.setStyleSheet("color: #626972;")
        spectrum_plotting_text.setAlignment(Qt.AlignCenter)
        spectrum_plotting_text.setWordWrap(True)
        spectrum_plotting_text.setMaximumHeight(50)

        self._autoscale_checkbox = QCheckBox(text = 'Autoscale y-axis')
        self._autoscale_checkbox.setChecked(False)
        self._autoscale_checkbox.stateChanged.connect(self._reset_autoscale)

        spectrum_plotting_widget = QWidget()
        spectrum_plotting_layout = QVBoxLayout()
        spectrum_plotting_widget.setLayout(spectrum_plotting_layout)
        spectrum_plotting_layout.addWidget(spectrum_plotting_text)
        spectrum_plotting_layout.addWidget(FigureCanvas(self.fig_plot_spectrum))
        spectrum_plotting_layout.addWidget(self._autoscale_checkbox)

        # VIPA raw data tab
        vipadata_widget = QWidget()
        vipadata_layout = QVBoxLayout()
        vipadata_widget.setLayout(vipadata_layout)
        vipadata_text = QLabel(text='Display the raw VIPA image of a single pixel in an active brimfile layer. If available, the spectral line is overlaid.')
        vipadata_text.setStyleSheet("color: #626972;")
        vipadata_text.setAlignment(Qt.AlignCenter)
        vipadata_text.setWordWrap(True)
        vipadata_text.setMaximumHeight(70)
        vipadata_layout.addWidget(vipadata_text)
        vipadata_layout.addWidget(FigureCanvas(self.fig_vipa_rawdata))

        # Spectral Image tab
        spectral_image_widget = QWidget()
        spectral_image_layout = QVBoxLayout()
        spectral_image_layout.setAlignment(Qt.AlignTop)
        spectral_image_widget.setLayout(spectral_image_layout)

        self._spectral_image_text = QLabel(text='Create a spectral image by integrating the spectrum in a frequency range for each pixel.\nSelect the frequency range and click the button to create the spectral image.')
        self._spectral_image_text.setStyleSheet("color: #626972;")
        self._spectral_image_text.setAlignment(Qt.AlignCenter)
        self._spectral_image_text.setWordWrap(True)
        self._num_label1 = QLabel("Lower bound")
        self._num_field1 = QDoubleSpinBox()
        self._num_field1.setRange(-100, 100)
        self._num_field1.setValue(-30)
        self._num_field1.setSingleStep(0.1)
        self._num_field1.setDecimals(2)
        self._num_field1.setSuffix(" GHz")
        self._num_field1.setMaximumWidth(150)
        self._num_field1.setLocale(QLocale(QLocale.English))  # ensure dot as decimal separator
        
        self._num_label2 = QLabel("Upper bound")
        self._num_field2 = QDoubleSpinBox()
        self._num_field2.setRange(-100, 100)
        self._num_field2.setValue(30)
        self._num_field2.setSingleStep(0.1)
        self._num_field2.setDecimals(2)
        self._num_field2.setSuffix(" GHz")
        self._num_field2.setMaximumWidth(150)
        self._num_field2.setLocale(QLocale(QLocale.English))  # ensure dot as decimal separator

        self._create_btn = QPushButton("Create spectral image")
        self._create_btn.clicked.connect(self._on_create_spectral_image)

        spectral_image_layout.addWidget(self._spectral_image_text)
        spectral_image_layout.addWidget(self._num_label1)
        spectral_image_layout.addWidget(self._num_field1)
        spectral_image_layout.addWidget(self._num_label2)
        spectral_image_layout.addWidget(self._num_field2)
        spectral_image_layout.addWidget(self._create_btn)
        
        # Regional Spectra tab
        # Based on a labels layer, create average spectra and shift histograms for each present label
        labels_widget = QWidget()
        labels_layout = QVBoxLayout()
        labels_widget.setLayout(labels_layout)

        labels_text = QLabel(text='Region-based analysis of Brillouin images. Select a brimfile layer. The dropdown will show available labels layers which can be used for the analysis. Select one and press "Analyse labels". The brimfile layer needs to remain the active selection.\nShow the average spectrum and summary statistics per region.')
        labels_text.setAlignment(Qt.AlignCenter)
        labels_text.setWordWrap(True)
        labels_text.setMaximumHeight(100)
        labels_text.setStyleSheet("color: #626972;")
        labels_layout.addWidget(labels_text)

        labels_selection_layout = QHBoxLayout()
        labels_layout.addLayout(labels_selection_layout)

        self._labels_combobox = QComboBox()
        # If new selection made, check if confirms.
        labels_new_button = QPushButton("Create new labels layer")
        labels_new_button.clicked.connect(self._create_labels_layer)
        labels_selection_layout.addWidget(self._labels_combobox)
        labels_selection_layout.addWidget(labels_new_button)
        # Add analyse button - then check if layer is eligible?
        labels_analyse_button = QPushButton("Analyse labels")
        labels_analyse_button.clicked.connect(self._plot_labels_spectrum)
        labels_layout.addWidget(labels_analyse_button)
        # Add plotting window
        labels_layout.addWidget(FigureCanvas(self.fig_regional_spectra))
        # Table for summary statistics
        self._labels_table = QTableWidget(0, 5) # label, mean shift, std shift, mean width, std width
        self._labels_table.setHorizontalHeaderLabels(["Label", "mean shift [GHz]", "std shift [GHz]", "mean width [GHz]", "std width [GHz]"])
        # self._labels_table.horizontalHeader().setStretchLastSection(True)
        self._labels_table.horizontalHeader().setSectionResizeMode(0, QHeaderView.ResizeToContents)
        self._labels_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self._labels_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self._labels_table.verticalHeader().setVisible(False)
        self._labels_table.setStyleSheet("""
                QTableWidget {
                    gridline-color: #3F4852;
                }
            """)
        labels_layout.addWidget(self._labels_table)


        # Add Widgets to tab
        tabs.addTab(inspect_metadata_widget, "Inspect Metadata")
        tabs.addTab(spectrum_plotting_widget, "Plot Spectrum at Pixel")
        self._vipa_tab_widget = vipadata_widget
        tabs.addTab(vipadata_widget, "VIPA Raw Data")
        # Hide the VIPA raw data tab if no brimfile layer with VIPA data is present
        self._update_vipa_tab_visibility()
        tabs.addTab(spectral_image_widget, "Create Spectral Image")
        tabs.addTab(labels_widget, "Regional Spectra Analysis")

        self._update_labels_combobox()
        self._viewer.layers.selection.events.changed.connect(self._update_labels_combobox)
        self._viewer.layers.events.inserted.connect(self._update_labels_combobox)
        self._viewer.layers.events.removed.connect(self._update_labels_combobox)

        self._viewer.layers.selection.events.changed.connect(self._update_vipa_tab_visibility)
        self._viewer.layers.events.inserted.connect(self._update_vipa_tab_visibility)
        self._viewer.layers.events.removed.connect(self._update_vipa_tab_visibility)

        self._update_metadata_table()
        self._viewer.layers.selection.events.changed.connect(self._update_metadata_table)
        self._viewer.layers.events.inserted.connect(self._update_metadata_table)
        self._viewer.layers.events.removed.connect(self._update_metadata_table)

        # Add Tabs widget to Napari widget
        self.native.layout().addWidget(tabs)

    def _update_vipa_tab_visibility(self, event=None):
        active_layer = self._viewer.layers.selection.active
        is_VIPA_brim = (
            active_layer is not None
            and bool(active_layer.metadata.get('is_brimfile'))
            and active_layer.metadata.get('brimfile') is not None
            and active_layer.metadata['brimfile'].subtype == brim.subtypes.SubType.SinglePoint_VIPA_v0_1
        )
        tab_index = self._tabs.indexOf(self._vipa_tab_widget)
        if tab_index >= 0:
            self._tabs.setTabVisible(tab_index, is_VIPA_brim)

    def _create_labels_layer(self):
        layer = self._viewer.layers.selection.active
        if layer is None:
            return
        if (('is_brimfile', True) not in layer.metadata.items()):
            napari.utils.notifications.show_info("A brimfile layer needs to be selected to create a labels layer.")
            return 
        # Create a new labels layer with the same shape as the active layer
        labels_data = np.zeros(layer.data.shape, dtype=np.uint8)
        self._viewer.add_labels(
            labels_data, 
            name=f"Labels for {layer.name}",
            scale=layer.scale,
            units=layer.units,
            )
    
    def _update_labels_combobox(self):
        # get all labels layers in the viewer and add to combobox
        self._labels_combobox.clear()
        active_layer = self._viewer.layers.selection.active
        if active_layer is None:
            return
        if (('is_brimfile', True) not in active_layer.metadata.items()):
            return  # ignore all other layers
        for layer in self._viewer.layers:
            if not isinstance(layer, napari.layers.Labels):
                continue
            layer_extent = np.array(layer.data.shape, dtype=float) * np.array(layer.scale, dtype=float)
            active_extent = np.array(active_layer.data.shape, dtype=float) * np.array(active_layer.scale, dtype=float)
            if np.allclose(layer_extent, active_extent):
                self._labels_combobox.addItem(layer.name)

    def _on_create_spectral_image(self):
        layer = self._viewer.layers.selection.active
        if (layer is None) or layer.visible == False:
                return
        # Check metadata attribute
        if (('is_brimfile', True) not in layer.metadata.items()):
            napari.utils.notifications.show_info("A brimfile layer needs to be selected to create a spectral image.")
            return  # ignore all other layers
        
        file = layer.metadata['brimfile']
        # go through every pixel and get sum intensity, then add to spectral image
        # get baseline from fit to substract
        image_PSD = file.get_data(layer.metadata['Data_group']).get_PSD_as_spatial_map() #[0] is intensities, [1] is frequencies
        image_offset = file.get_data(layer.metadata['Data_group']).get_analysis_results(layer.metadata['Analysis_result']).get_image(brim.Data.AnalysisResults.Quantity.Offset)[0][:,:,:,np.newaxis]
        image_ampl = image_PSD[0] - image_offset
        if self._num_field1.value() > self._num_field2.value():
            tmp = self._num_field1.value()
            self._num_field1.setValue(self._num_field2.value())
            self._num_field2.setValue(tmp)
        image_mask = (image_PSD[1] >= self._num_field1.value()) & (image_PSD[1] <= self._num_field2.value())
        image_ampl = image_ampl * image_mask
        image_mask = np.sum(image_mask, axis=-1)
        spectral_img = np.divide(np.sum(image_ampl, axis=-1), image_mask, where=image_mask!=0)
        if np.any(image_mask == 0):
            napari.utils.notifications.show_info("Some pixels had no valid data in the selected frequency range.")
        
        try:
            self._viewer.add_image(
                spectral_img, 
                name=f'Spectral image from {np.round(self._num_field1.value(), decimals=2)} to {np.round(self._num_field2.value(), decimals=2)} GHz',
                scale=layer.scale,
                units=layer.units,
                )
        except Exception:
            print("Failed to add spectral image layer")

    def _connect_mouse_events(self):
        def on_click(viewer, event):
            layer = viewer.layers.selection.active
            if layer is None:
                return
            # Check metadata attribute
            if (('is_brimfile', True) not in layer.metadata.items()):
                return  # ignore all other layers
            
            dragged = False
            yield
            # on move
            while event.type == 'mouse_move':
                dragged = True
                yield
            # on release
            if dragged:
                return
            else:
                # Now handle the click
                coord = layer.world_to_data(event.position) 
                coord = np.round(np.array(coord)).astype(int)
                self._load_spectrum(tuple(coord), layer)
                self._load_VIPA_rawdata(tuple(coord), layer)

        # Attach callback to the viewer (not to each layer)
        self._viewer.mouse_drag_callbacks.append(on_click)

    def _reset_autoscale(self):
        self.spectrum_ymax = 0
        self.spectrum_ymin = 1E6
    
    def _mouse_event_is_valid(self, coord, image_layer):
        if image_layer.visible == False:
            return False
        # check if coords are within image
        image_shape = image_layer.data.shape
        for i in range(len(image_shape)):
            if (coord[i] < 0) | (coord[i] > image_shape[i]-1):
                return False
        return True

    def _linewidth_data_to_points(self, linewidth_data, x_start, y_start, x_end, y_end):
        """Convert a linewidth in image data units (pixels) to matplotlib points."""
        #TODO: check if this methd is robust to scaling of the axis
        # look at https://stackoverflow.com/questions/43495016/matplotlib-line-width-based-on-axis-not-on-points for alternative methods
        if linewidth_data is None:
            linewidth_data = 1.0
        linewidth_data = float(linewidth_data)
        if linewidth_data <= 0:
            return 0.1

        # Build a unit normal to the spectral line in data coordinates.
        dx = float(x_end) - float(x_start)
        dy = float(y_end) - float(y_start)
        seg_len = np.hypot(dx, dy)
        if seg_len == 0:
            nx, ny = 1.0, 0.0
        else:
            nx, ny = -dy / seg_len, dx / seg_len

        xm = 0.5 * (float(x_start) + float(x_end))
        ym = 0.5 * (float(y_start) + float(y_end))
        p0 = self.ax_vipa_rawdata.transData.transform((xm, ym))
        p1 = self.ax_vipa_rawdata.transData.transform((xm + nx * linewidth_data, ym + ny * linewidth_data))
        linewidth_pixels = float(np.hypot(*(p1 - p0)))
        linewidth_points = linewidth_pixels * 72.0 / self.fig_vipa_rawdata.dpi

        return max(linewidth_points, 0.1)

    def _load_VIPA_rawdata(self, coord, image_layer):
        if not self._mouse_event_is_valid(coord, image_layer):
            return
        file = image_layer.metadata['brimfile']
        if file.subtype != brim.subtypes.SubType.SinglePoint_VIPA_v0_1:
            return
        data_group = file.get_data(image_layer.metadata['Data_group'])
        raw_image, spectral_line, linewidth = single_point_VIPA.get_raw_spectrum_in_image(data_group, coord)
        raw_image = np.asarray(raw_image)

        self.ax_vipa_rawdata.clear()
        self.ax_vipa_rawdata.set_axis_off()
        self.ax_vipa_rawdata.imshow(raw_image, cmap='gray', origin='upper')
        if spectral_line is not None:
            y_start, x_start, y_end, x_end = spectral_line
            linewidth_data = linewidth if linewidth is not None else 1.0
            linewidth_points = self._linewidth_data_to_points(
                linewidth_data,
                x_start,
                y_start,
                x_end,
                y_end,
            )
            self.ax_vipa_rawdata.plot(
                [x_start, x_end],
                [y_start, y_end],
                color="#D27F75",
                alpha=0.2,
                linewidth=linewidth_points,
                solid_capstyle='round',
            )
        self.ax_vipa_rawdata.set_title(
            f'Raw VIPA image at pixel [{coord[0]},{coord[1]},{coord[2]}]',
            color='white',
            fontsize=12,
        )
        self.fig_vipa_rawdata.canvas.draw()

    def _load_spectrum(self, coord, image_layer):
        if not self._mouse_event_is_valid(coord, image_layer):
            return
        file = image_layer.metadata['brimfile']

        # plot spectrum
        spectrum = file.get_data(image_layer.metadata['Data_group']).get_spectrum_in_image(coord)
        spectrum_sorted = np.array([spectrum[0], spectrum[1]])[:,np.lexsort(np.array([spectrum[0], spectrum[1]]))]
        spectrum_sorted = spectrum_sorted[:,np.logical_not(np.isnan(spectrum_sorted[1]))]
        if self.spectrum_ymax < max(spectrum_sorted[0]):
            self.spectrum_ymax = max(spectrum_sorted[0])
        if self.spectrum_ymin > min(spectrum_sorted[0]):
            self.spectrum_ymin = min(spectrum_sorted[0])
        self.ax_plot_spectrum.clear()
        # Check if part of the spectrum is missing
        frequ_diffs = np.diff(spectrum_sorted[1])
        frequ_spacing = np.median(frequ_diffs)
        frequ_jumps = np.where(frequ_diffs > 2*frequ_spacing)[0]
        if len(frequ_jumps) == 0:
            self.ax_plot_spectrum.plot(spectrum[1], spectrum[0], color = "#2B2E37", lw=2)
        else: # split 
            frequ_jumps = np.concatenate([[0],frequ_jumps+1,[len(spectrum_sorted[1,:])]])      # 0 i, i j, j -1
            for i in range(len(frequ_jumps)-1):
                self.ax_plot_spectrum.plot(
                    spectrum_sorted[1,frequ_jumps[i]:frequ_jumps[i+1]], 
                    spectrum_sorted[0,frequ_jumps[i]:frequ_jumps[i+1]], 
                    color = "#2B2E37", 
                    lw = 2)
        # Load fits
        fit_model = brim.fitting_models.get_fit_model(file.get_data(image_layer.metadata['Data_group']).get_analysis_results(image_layer.metadata['Analysis_result']).fit_model)
        px_quantities = file.get_data(image_layer.metadata['Data_group']).get_analysis_results(image_layer.metadata['Analysis_result']).get_all_quantities_in_image(coord)
        fit_x = np.arange(np.min(spectrum_sorted[1]), np.max(spectrum_sorted[1]),0.1)
        for itype in ['Stokes', 'AntiStokes']:
            if itype not in px_quantities['Shift']:
                continue
            nu0 = px_quantities['Shift'][itype].value
            gamma = px_quantities['Width'][itype].value
            a = px_quantities['Amplitude'][itype].value
            b = px_quantities['Offset'][itype].value
            self.ax_plot_spectrum.plot(fit_x, fit_model(fit_x, nu0, gamma, a, b), color = "#2FA489", lw=1.5, ls = ':')        
        
        # Update figure and axes 
        self.ax_plot_spectrum.set_xlabel('Frequency [{}]'.format(spectrum[3]), color='white')
        self.ax_plot_spectrum.set_ylabel('PSD', color='white')
        if not self._autoscale_checkbox.isChecked():
            self.ax_plot_spectrum.set_ylim(self.spectrum_ymin, self.spectrum_ymax)
        self.ax_plot_spectrum.set_title('Spectrum of ' + image_layer.name + '\nat pixel [{},{},{}]'.format(coord[0],coord[1],coord[2]), color='White', fontsize = 12)
        self.fig_plot_spectrum.canvas.draw()

    def _update_metadata_table(self):
        self._metadata_table.setRowCount(0)
        active_layer = self._viewer.layers.selection.active
        if active_layer is None:
            return
        if ('is_brimfile', True) not in active_layer.metadata.items():
            return
        brim_metadata = active_layer.metadata['brimfile'].get_data(active_layer.metadata['Data_group']).get_metadata().all_to_dict()
        # Traverse the nested metadata dict (outer_key -> inner_key -> item) and populate table
        for outer_key, inner_dict in brim_metadata.items():
            if isinstance(inner_dict, dict):
                # Add header row for outer_key
                row = self._metadata_table.rowCount()
                self._metadata_table.insertRow(row)
                header_item = QTableWidgetItem(outer_key)
                header_item.setFlags(Qt.ItemIsEnabled)  # make header row non-selectable
                header_item.setBackground(QColor("#3F4852"))
                header_item.setForeground(QColor("#D1D2D4"))
                header_item.setTextAlignment(Qt.AlignCenter)
                self._metadata_table.setItem(row, 0, header_item)
                self._metadata_table.setSpan(row, 0, 1, 2) # span both columns

                for inner_key, item in inner_dict.items():
                    if (inner_key == 'IRF') or (inner_key == 'IRF_frequency'):
                        continue  # skip IRF data for display
                    row = self._metadata_table.rowCount()
                    self._metadata_table.insertRow(row)
                    unit = item.units if hasattr(item, 'units') else False
                    if unit:
                        self._metadata_table.setItem(row, 0, QTableWidgetItem(f"{inner_key} [{unit}]"))
                    else: 
                        self._metadata_table.setItem(row, 0, QTableWidgetItem(f"{inner_key}"))
                    value = item.value if hasattr(item, 'value') else str(item)
                    self._metadata_table.setItem(row, 1, QTableWidgetItem(str(value)))
            else:
                napari.utils.notifications.show_info("Check if brimfile metadata are valid.")

    def _plot_labels_spectrum(self):
        if self._labels_combobox.currentText() == "":
            napari.utils.notifications.show_info("Select a brimfile layer and choose a labels layer.")
            return 
        # get all pixels with label
        labels_layer = self._viewer.layers[self._labels_combobox.currentText()]
        labels = labels_layer.data
        n_labels = np.unique(labels[labels>0])
        if len(n_labels) == 0:
            napari.utils.notifications.show_info("No labels found in the selected layer.")
            return
        
        brim_layer = self._viewer.layers.selection.active
        if (brim_layer is None) or (('is_brimfile', True) not in brim_layer.metadata.items()):
            napari.utils.notifications.show_info("A brimfile layer needs to be selected.")
            return
        file = brim_layer.metadata['brimfile']

        psd0, psd1,_,freq_unit = file.get_data(brim_layer.metadata['Data_group']).get_PSD_as_spatial_map()
        idx = np.argsort(psd1, axis=-1)
        psd1_sorted = np.take_along_axis(psd1, idx, axis=-1)
        psd0_sorted = np.take_along_axis(psd0, idx, axis=-1)
        # keep as tuple
        psd_sorted = np.array([psd0_sorted, psd1_sorted])
        freq_min = np.nanmin(psd_sorted[1,...])
        freq_max = np.nanmax(psd_sorted[1,...])
        common_freqs = np.arange(freq_min, freq_max, 0.01)
        common_psd = np.full((psd0.shape[0], psd0.shape[1], psd0.shape[2], len(common_freqs)), np.nan)
        #labelled_pixels = np.argwhere(labels>0)

        for iz in range(psd_sorted.shape[1]):
            for iy in range(psd_sorted.shape[2]):
                for ix in range(psd_sorted.shape[3]):
                    # TODO: implement efficiency to only interpolate pixels within the mask
                    #if np.any(np.all(labelled_pixels == [iz,iy,ix], axis=1)):
                    #    continue
                    valid = ~(np.isnan(psd_sorted[1, iz, iy, ix,:]) | np.isnan(psd_sorted[0, iz, iy, ix,:]))
                    frequ_diffs = np.diff(psd_sorted[1, iz, iy, ix,valid], axis=-1)
                    frequ_spacing = np.median(frequ_diffs)
                    frequ_jumps = np.where(frequ_diffs > 2*frequ_spacing)[0]
                    if len(frequ_jumps) == 0:
                        # interpolate and add to common freq array
                        cs = interpolate.CubicSpline(psd_sorted[1, iz, iy, ix,valid], psd_sorted[0, iz, iy, ix,valid])
                        covered_freqs = (common_freqs >= np.min(psd_sorted[1, iz, iy, ix,valid])) & (common_freqs <= np.max(psd_sorted[1, iz, iy, ix,valid]))
                        common_psd[iz, iy, ix, covered_freqs] = cs(common_freqs[covered_freqs])
                    else:
                        # interpolate every continuous part and add to common freq array
                        frequ_jumps = np.concat([[0],frequ_jumps+1,[len(psd_sorted[1, iz, iy, ix,valid])]])      # 0 i, i j, j -1
                        for ifreq in range(len(frequ_jumps)-1):
                            x = psd_sorted[1, iz, iy, ix,frequ_jumps[ifreq]:frequ_jumps[ifreq+1]]
                            y = psd_sorted[0, iz, iy, ix,frequ_jumps[ifreq]:frequ_jumps[ifreq+1]] 
                            cs = interpolate.CubicSpline(x, y)
                            covered_freqs = (common_freqs >= np.min(x)) & (common_freqs <= np.max(x))
                            common_psd[iz, iy, ix, covered_freqs] = cs(common_freqs[covered_freqs])

        self.ax_regional_spectra.clear()
        self._labels_table.setRowCount(0)
        averaged_spectra = {}
        legend_labels = []
        for ilab in n_labels:
            mask = labels == ilab
            # get spectra for all pixels and average
            spectra = np.zeros(len(common_freqs))
            n_spectra = np.sum(mask)
            for coord in np.argwhere(mask):
                spectra += common_psd[coord[0], coord[1], coord[2], :]
            averaged_spectra[ilab] = spectra / n_spectra

            valid = ~np.isnan(averaged_spectra[ilab])
            frequ_diffs = np.diff(common_freqs[valid])
            frequ_spacing = np.median(frequ_diffs)
            frequ_jumps = np.where(frequ_diffs > 2*frequ_spacing)[0]
            if len(frequ_jumps) == 0:
                spectra1, = self.ax_regional_spectra.plot(common_freqs[valid], averaged_spectra[ilab][valid], label = f'Label {ilab}', color = labels_layer.get_color(ilab))
                legend_labels.append(spectra1)
            else: # split 
                frequ_jumps = np.concat([[0],frequ_jumps+1,[len(common_freqs[valid])]])      # 0 i, i j, j -1
                for i in range(len(frequ_jumps)-1):
                    spectra1, = self.ax_regional_spectra.plot(
                        common_freqs[valid][frequ_jumps[i]:frequ_jumps[i+1]], 
                        averaged_spectra[ilab][valid][frequ_jumps[i]:frequ_jumps[i+1]], 
                        label = f'Label {ilab}',
                        lw = 2,
                        color = labels_layer.get_color(ilab),
                        )
                    if i == 0:
                        legend_labels.append(spectra1)
            
            # Update summary table
            row = self._labels_table.rowCount()
            self._labels_table.insertRow(row)
            self._labels_table.setItem(row, 0, QTableWidgetItem(f"{ilab}"))
            try:
                shift_img = file.get_data(brim_layer.metadata['Data_group']).get_analysis_results(brim_layer.metadata['Analysis_result']).get_image(brim.AnalysisResults.Quantity.Shift)[0]
            except:
                shift_img = None
            try:    
                width_img = file.get_data(brim_layer.metadata['Data_group']).get_analysis_results(brim_layer.metadata['Analysis_result']).get_image(brim.AnalysisResults.Quantity.Width)[0]
            except:
                width_img = None
            if shift_img is not None:
                mean_shift = np.round(np.nanmean(shift_img[mask]),3)
                std_shift = np.round(np.nanstd(shift_img[mask]),3)
                self._labels_table.setItem(row, 1, QTableWidgetItem(str(mean_shift)))
                self._labels_table.setItem(row, 2, QTableWidgetItem(str(std_shift)))
            if width_img is not None:
                mean_width = np.round(np.nanmean(width_img[mask]),3)
                std_width = np.round(np.nanstd(width_img[mask]),3)
                self._labels_table.setItem(row, 3, QTableWidgetItem(str(mean_width)))
                self._labels_table.setItem(row, 4, QTableWidgetItem(str(std_width)))
            
        self.ax_regional_spectra.set_xlabel('Frequency [{}]'.format(freq_unit), color='white')
        self.ax_regional_spectra.set_ylabel('PSD', color='white')   
        self.ax_regional_spectra.legend(
            handles=legend_labels,
            loc='upper center',
            bbox_to_anchor=(0.5, 1.2),   # x=centre, y=below axes
            ncols=3,   
            )
        self.fig_regional_spectra.canvas.draw()
        self.fig_regional_spectra.get_layout_engine().set(rect=(0, 0, 1, 0.9))

        