name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Setup python
      uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
      with:
        python-version: ${{ matrix.python-version }}
        activate-environment: "true"

    - name: Setup headless display
      uses: pyvista/setup-headless-display-action@v4
      with:
        qt: true
        wm: herbstluftwm

    - name: Test with tox
      run: uvx --with tox-gh-actions tox
      env:
        PLATFORM: ${{ matrix.os }}
